training_data_paths:
- [
  'data/bilibili/csv/bilibili_20250616_204043_10h_android_16.csv',
  'data/bilibili/csv/bilibili_20250716_101749_5h_android_18.csv',
  'data/bilibili/csv/bilibili_20250717_191237_50400_android_17.csv',
  'data/bilibili/csv/bilibili_20250718_101704_25200_android_19.csv',
]
- [
  'data/wenxiaoyan/csv/wenxiaoyan_20250726_172552_129600_android_16.csv',
  'data/wenxiaoyan/csv/wenxiaoyan_20250804_204806_144000_android_17.csv',
  'data/wenxiaoyan/csv/wenxiaoyan_20250804_205024_144000_android_18.csv',
  'data/wenxiaoyan/csv/wenxiaoyan_20250804_205029_144000_android_19.csv',
]

model_path_pkl: result/model_classifier_2.pkl
scaler_path_pkl: result/scaler_2.pkl
model_path_onnx: result/model_classifier_2.onnx
scaler_path_json: result/scaler_params_2.json

evaluation_data_paths:
  - ['data/bilibili/csv/bilibili_20250721_141827_21600_android_20.csv']
  - ['data/wenxiaoyan/csv/wenxiaoyan_20250804_205038_144000_android_20.csv']

output_dir: result
classification_report_file: result/classification_report_2.txt
predictions_detail_file: result/predictions_detail_2.csv

onnx_log_level: WARNING
columns_to_remove: [0, 1, 2]
filter_packets: 16